version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"  # Mapeia a porta 80 do container para a porta 8080 do host
    volumes:
      - ./app:/var/www/html/app  # Mapeia a pasta 'app' para o diretório do Apache no container
    depends_on:
      - mysql  # Garante que o MySQL inicie primeiro

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do root do MySQL
      MYSQL_DATABASE: controle_empresa  # Banco de dados que será criado ao iniciar
    ports:
      - "3306:3306"  # Mapeia a porta do MySQL para o host
